spring:
  application:
    name: FGS
  profiles:
    active: dev
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
server:
  port: 80
  servlet:
    context-path: /fgs/api
    session:
      timeout: 600s
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: system.domain

#开发环境
---

spring:
  profiles: dev
  datasource:                                              #配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sys_oss?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    system: debug

---
spring:
  mail:
    password: zycdwr1024
    port: 587
    host: smtp-mail.outlook.com
    properties:
      mail:
        smtp:
          starttls:
            required: true
    username: zyc199777@outlook.com
  datasource:
    druid:
      min-idle: 1
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        principal-cookie-name: admin
        session-stat-enable: false
        url-pattern: /*
        session-stat-max-count: 1000
        exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
        profile-enable: true
        principal-session-name: admin
        enabled: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      max-active: 20
      max-wait: 60000
      test-on-borrow: false
      stat-view-servlet:
        url-pattern: /druid/*
        login-password:
        reset-enable: true
        login-username:
        enabled: true
      pool-prepared-statements: true
      initial-size: 1
      min-evictable-idle-time-millis: 300000
      test-on-return: false
