spring:
  application:
    name: FGS
  profiles:
    active: dev
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  redis:
    password: Zycrds1024
server:
  port: 8090
  servlet:
    context-path: /fgs-api
    session:
      timeout: 600s
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: system.entity
token:
  expire:
    seconds: 7200
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)

#开发环境
---

spring:
  profiles: dev
  datasource:                                              #配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bysj_fgs?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  file: spring_fgs.log
  level:
    system: debug



